# Generated by Django 3.0.2 on 2020-02-17 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecuirtmentModel',
            fields=[
                ('oppcode', models.IntegerField(primary_key=True, serialize=False)),
                ('qualification', models.CharField(max_length=30)),
                ('regi_form', models.DateField()),
                ('age', models.IntegerField()),
                ('lastdob', models.DateField()),
                ('department', models.CharField(choices=[('DEVELOPER', 'DEVELOPER'), ('TESTER', 'tester'), ('designer', 'DESIGNER'), ('MANAGER', 'manager')], max_length=40)),
                ('positions', models.IntegerField()),
                ('description', models.CharField(max_length=100)),
                ('respon', models.CharField(max_length=50)),
                ('contactno', models.IntegerField(unique=True)),
            ],
        ),
    ]
