# Generated by Django 3.0.2 on 2020-02-18 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0002_recuirtmentmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recuirtmentmodel',
            name='lastdob',
            field=models.DateField(help_text='yyyy-mm-dd'),
        ),
        migrations.AlterField(
            model_name='recuirtmentmodel',
            name='regi_form',
            field=models.DateField(help_text='yyyy-mm-dd'),
        ),
    ]
