# Generated by Django 3.0.2 on 2020-02-24 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0004_interviewshedulemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewshedulemodel',
            name='selectempid',
            field=models.IntegerField(),
        ),
    ]
