# Generated by Django 3.0.2 on 2020-02-26 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='interviewModel',
            fields=[
                ('interviewid', models.IntegerField(primary_key=True, serialize=False)),
                ('interviewer', models.IntegerField(unique=True)),
                ('scheduledate', models.DateField()),
                ('applicantid', models.IntegerField(unique=True)),
                ('result', models.CharField(max_length=40)),
            ],
        ),
    ]
