# Generated by Django 3.0.2 on 2020-02-25 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Applicant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('dateofbirth', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.CharField(max_length=15)),
                ('mobile', models.IntegerField(unique=True)),
                ('address', models.CharField(max_length=100)),
                ('qualification', models.CharField(max_length=30)),
                ('post', models.CharField(max_length=40)),
                ('per', models.IntegerField()),
                ('file', models.FileField(upload_to='file_image/')),
            ],
        ),
    ]
