# Generated by Django 3.0.2 on 2020-02-26 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Applicant', '0002_applicationmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicationmodel',
            old_name='address',
            new_name='addres',
        ),
        migrations.RenameField(
            model_name='applicationmodel',
            old_name='dateofbirth',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='applicationmodel',
            old_name='email',
            new_name='emaii',
        ),
        migrations.RenameField(
            model_name='applicationmodel',
            old_name='gender',
            new_name='gende',
        ),
        migrations.RenameField(
            model_name='applicationmodel',
            old_name='mobile',
            new_name='mobil',
        ),
        migrations.RenameField(
            model_name='applicationmodel',
            old_name='name',
            new_name='nam',
        ),
        migrations.RenameField(
            model_name='applicationmodel',
            old_name='per',
            new_name='perce',
        ),
        migrations.RenameField(
            model_name='applicationmodel',
            old_name='qualification',
            new_name='qualificatio',
        ),
        migrations.AlterField(
            model_name='applicationmodel',
            name='file',
            field=models.FileField(upload_to='files_images/'),
        ),
    ]
