# Generated by Django 3.0.2 on 2020-02-12 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminModel',
        ),
    ]
